USE master
GO

CREATE DATABASE SQL#Presentation
GO

ALTER DATABASE [SQL#Presentation] SET ANSI_NULL_DEFAULT OFF 
ALTER DATABASE [SQL#Presentation] SET ANSI_NULLS OFF 
ALTER DATABASE [SQL#Presentation] SET ANSI_PADDING OFF 
ALTER DATABASE [SQL#Presentation] SET ANSI_WARNINGS OFF 
ALTER DATABASE [SQL#Presentation] SET ARITHABORT OFF 
ALTER DATABASE [SQL#Presentation] SET AUTO_CLOSE OFF 
ALTER DATABASE [SQL#Presentation] SET AUTO_CREATE_STATISTICS ON 
ALTER DATABASE [SQL#Presentation] SET AUTO_SHRINK OFF 
ALTER DATABASE [SQL#Presentation] SET AUTO_UPDATE_STATISTICS ON 
ALTER DATABASE [SQL#Presentation] SET CURSOR_CLOSE_ON_COMMIT OFF 
ALTER DATABASE [SQL#Presentation] SET CURSOR_DEFAULT  GLOBAL 
ALTER DATABASE [SQL#Presentation] SET CONCAT_NULL_YIELDS_NULL OFF 
ALTER DATABASE [SQL#Presentation] SET NUMERIC_ROUNDABORT OFF 
ALTER DATABASE [SQL#Presentation] SET QUOTED_IDENTIFIER OFF 
ALTER DATABASE [SQL#Presentation] SET RECURSIVE_TRIGGERS OFF 
ALTER DATABASE [SQL#Presentation] SET ENABLE_BROKER 
ALTER DATABASE [SQL#Presentation] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
ALTER DATABASE [SQL#Presentation] SET DATE_CORRELATION_OPTIMIZATION OFF 
ALTER DATABASE [SQL#Presentation] SET TRUSTWORTHY ON 
ALTER DATABASE [SQL#Presentation] SET ALLOW_SNAPSHOT_ISOLATION OFF 
ALTER DATABASE [SQL#Presentation] SET PARAMETERIZATION SIMPLE 
ALTER DATABASE [SQL#Presentation] SET READ_COMMITTED_SNAPSHOT OFF 
ALTER DATABASE [SQL#Presentation] SET HONOR_BROKER_PRIORITY OFF 
ALTER DATABASE [SQL#Presentation] SET RECOVERY SIMPLE
ALTER DATABASE [SQL#Presentation] SET MULTI_USER 
ALTER DATABASE [SQL#Presentation] SET PAGE_VERIFY CHECKSUM  
ALTER DATABASE [SQL#Presentation] SET DB_CHAINING OFF 
ALTER DATABASE [SQL#Presentation] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
ALTER DATABASE [SQL#Presentation] SET TARGET_RECOVERY_TIME = 0 SECONDS 
ALTER DATABASE [SQL#Presentation] SET READ_WRITE 